class TestsConfig:
    HUGGINGFACE_EMBEDDINGS = "all-MiniLM-L6-v2"
    OLLAMA_MODEL = "llama3"
    GEMINI_LLM_MODEL = "gemini-2.5-flash"
    GEMINI_EMBEDDING_MODEL = "models/gemini-embedding-001"
    CHROMA_PERSIST_DIRECTORY = "/Users/labess40/dev/RAGLight/chromaDb"
    CHROMA_PERSIST_DIRECTORY_INGESTION = "/Users/labess40/dev/RAGLight/chromaDb2"
    TEST_SYSTEM_PROMPT = "tests/prompts/prompt.txt"
    COLLECTION_NAME = "grece"
    # DATA_PATH = "/Users/labess40/Desktop/nutrition/grece"
    DEFAULT_OLLAMA_CLIENT = "http://192.168.1.103:11434"
    DATA_PATH = "/home/danesh/Documents/Out"
    OLLAMA_EMBEDDING_MODEL="nomic-embed-text:v1.5"
    POSTGRES_HOST = "192.168.1.103"
    POSTGRES_PORT=5432
    POSTGRES_DATABASE="ai_db"
    POSTGRES_USER="postgres"
    POSTGRES_PASSWORD=""
